version: "3.8"
services:
  db:
    image: "postgres:13.6"
    container_name: pg-docker
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2022
      - POSTGRES_DB=fin_db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin2022
    ports:
      - "5050:80"

networks:
  default:
    name: fin-network
